version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      PYTHONPATH: /app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
  mlflow:
    image: mlflow
    ports:
      - 5000:5000
  airflow:
    image: puckel/docker-airflow
    environment:
      - EXECUTOR=Local
    ports:
      - 8080:8080
    volumes:
      - ./src/dags:/usr/local/airflow/dags
