name: Preview documentation

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate documentation
      run: |
        # run your documentation generation command here
        make html

    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        publish_dir: docs/_build

    - name: Comment on PR with deployment link
      uses: peter-evans/create-or-update-pull-request-comment@v2
      env:
        GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
      with:
        body: {% raw %}"Documentation deployed to https://${{ env.GITHUB_ACTOR }}.github.io/${{ env.GITHUB_REPOSITORY }}/${{ env.GITHUB_HEAD_REF }}"{% endraw %}
